repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/kynan/nbstripout
    rev: 0.3.9
    hooks:
    - id: nbstripout
      args: ["--keep-output"]

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.1.1
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
      - id: nbqa-flake8
