name: pylandstats
channels:
  - conda-forge
  - bioconda
dependencies:
  - geopandas
  - ipykernel
  - matplotlib>=3.4
  - osmnx>=1
  - papermill
  - pre-commit
  - pygeos
  - pylandstats=2.4.2
  - python=3.10
  - seaborn
  - snakemake
  - swisslandstats-geopy=0.10.0
