name: pylandstats
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - descartes
  - geopandas
  - ipykernel
  - osmnx>=1
  - papermill
  - pre-commit
  - pylandstats
  - pyproj
  - python=3
  - snakemake=6.8.0
  - swisslandstats-geopy=0.9.0
