name: pylandstats
channels:
  - conda-forge
  - bioconda
dependencies:
  - contextily
  - geopandas=1
  - ipykernel
  - matplotlib>=3.4
  - osmnx>=1
  - papermill
  - pip
  - pip:
      - pylandstats==3.1.0
  - pre-commit
  - python=3.12
  - seaborn
  - snakemake
  - swisslandstats-geopy=0.12.0
