name: pylandstats
channels:
  - conda-forge
  - bioconda
dependencies:
  - contextily
  - geopandas
  - ipykernel
  - matplotlib>=3.4
  - osmnx>=1
  - papermill
  - pip
  - pip:
      - pylandstats=3.0.0
  - pre-commit
  - pygeos
  - python=3.10
  - seaborn
  - snakemake
  - swisslandstats-geopy=0.12.0
