name: pylandstats
channels:
  - conda-forge
  - defaults
dependencies:
  - descartes
  - geopandas
  - ipykernel
  - matplotlib>=3.4
  - osmnx>=1
  - papermill
  - pre-commit
  - pygeos
  - pylandstats=2.4.2
  - pyproj
  - python=3
  - seaborn
  - swisslandstats-geopy=0.10.0
