name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            environment-file: environment.yml
            miniforge-variant: Mambaforge
            miniforge-version: 4.9.2-4

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          activate-environment: pylandstats
          condarc-file: ${{ matrix.condarc-file }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}

      - name: Register ipykernel
        run: |
          snakemake -c1 register_ipykernel

      - name: Preprocess LULC data
        run: |
          snakemake -c1 lulc_tifs

      - name: Test notebooks
        run: |
          snakemake -c1 run_notebooks
